#Docker File for Integrator
FROM node:12.14.1-alpine3.10

LABEL maintainer="Team Cloud - Stefanini"

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY ./code/package*.json ./

RUN npm install -g pm2
RUN npm install

COPY ./code .

COPY --chown=node:node ./code .

#USER node

RUN npm run build

ENTRYPOINT ["sh", "./entrypoint.sh"]
